config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogposts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'blogposts#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
	# Define abilities for the passed in user here. For example:
	#
	#   user ||= User.new # guest user (not logged in)
	#   if user.admin?
	#     can :manage, :all
	#   else
	#     can :read, :all
	#   end
	#
	# The first argument to `can` is the action you are giving the user
	# permission to do.
	# If you pass :manage it will apply to every action. Other common actions
	# here are :read, :create, :update and :destroy.
	#
	# The second argument is the resource the user can perform the action on.
	# If you pass :all it will apply to every resource. Otherwise pass a Ruby
	# class of the resource.
	#
	# The third argument is an optional hash of conditions to further filter the
	# objects.
	# For example, here the user can only update published articles.
	#
	#   can :update, Article, :published => true
	#
	# See the wiki for details:
	# https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new 
    if user.admin?
      can :manage, :all
  	else
      can :read, :all
      can :manage, Blogpost, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :blogposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
      redirect_to main_app.root_url, alert: exception.message
  end

  # amend Devise security to permit User.name field to be handled along with Devise fields
  before_action :configure_permitted_parameters, if: :devise_controller?
    protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_action :set_blogpost, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  helper_method :sort_column, :sort_direction

  # GET /blogposts
  # GET /blogposts.json
  def index
    #@blogposts = Blogpost.all
    @blogposts = Blogpost.order("#{sort_column} #{sort_direction}")
  end

  # GET /blogposts/1
  # GET /blogposts/1.json
  def show
  end

  # GET /blogposts/new
  def new
    @blogpost = Blogpost.new
  end

  # GET /blogposts/1/edit
  def edit
  end

  # POST /blogposts
  # POST /blogposts.json
  def create
    @blogpost = Blogpost.new(blogpost_params)
    @blogpost.user = current_user
    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully created.' }
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogposts/1
  # PATCH/PUT /blogposts/1.json
  def update
    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogposts/1
  # DELETE /blogposts/1.json
  def destroy
    @blogpost.destroy
    respond_to do |format|
      format.html { redirect_to blogposts_url, notice: 'Blogpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogpost
      @blogpost = Blogpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogpost_params
      params.require(:blogpost).permit(:subject, :blogentry, :author, :blogdate, :image_url)
    end

    def sortable_columns
      ["updated_at"]
    end

    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : "updated_at"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/views/blogposts/_form.html.erb
<%= form_with(model: blogpost, local: true) do |form| %>
  <% if blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul>
      <% blogpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-offset-2 col-md-8 col-md-offset-2 work-box">
    <div class="form-inline">
      <div class="form-group  textfield-full">
        <div class="input-group textfield-medium">
          <label for="blogpost_author">Author</label>
          <%= form.text_field :author, id: :blogpost_author, value: current_user.name, readonly: "readonly", class: "form-control" %>
        </div><!-- /input-group author -->
        <div class="input-group push-right">
          <label for="blogpost_blogdate">Date</label>
          <%= form.date_select :blogdate, id: :blogpost_blogdate, class: "form-control" %>  
        </div><!--/input-group date -->
      </div><!-- /form group -->
    </div><!-- /form-inline -->

    <div class="field">
      <p>Subject</p>
      <!--<%= form.label :subject %>-->
      <%= form.text_field :subject, id: :blogpost_subject, autofocus: true, class: "textfield-full" %>
    </div><!--/field subject -->

    <div class="field">
      <p>Entry</p>
      <!-- <%= form.label :blogentry %> -->
      <%= form.text_area :blogentry, id: :blogpost_blogentry, class: "textarea-full" %>
    </div><!-- field blog entry -->

<!--    <div class="field">     // Add image support later
      <p>Image URL</p>
      <#%= form.label :image_url %> 
      <#%= form.text_field :image_url, id: :blogpost_image_url %>
    </div>
-->
    <div class="actions bottom-of-page">
      <%= form.submit "Submit Entry", class: "btn btn-primary" %>
    </div>
  </div><!-- /work-box -->
<% end %>

app/views/blogposts/edit.html.erb
<h1 class="col-md-offset-2 col-md-8 col-md-offset-2">
  Edit Blog Post
</h1>

<%= render 'form', blogpost: @blogpost %>

<!-- <%= link_to 'Show', @blogpost %> | -->
<!--<%= link_to 'Back', blogposts_path %>-->

app/views/blogposts/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<div class="col-md-offset-2 col-md-8 col-md-offset-2">
  <h1>Bomymo Blog</h1>
  <h3>Blog your heart out</h3>
</div><!-- /header-indent -->

<div class="col-md-offset-2 col-md-8 col-md-offset-2 work-box bottom-of-page">
  <% @blogposts.each do |blogpost| %>
    <p class="display-subject"><a href="/blogposts/<%= blogpost.id %>"><%= blogpost.subject %></a></p>
    <p class="entry-summary">
      <%= blogpost.blogentry[0, 100] %>...
      <div class="align-right">
        <% if current_user %>
          <% if blogpost.user_id == current_user.id %>
            <%= link_to 'Edit', edit_blogpost_path(blogpost) %>
            <%= link_to 'Delete', blogpost, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        <% end %>
      </div>
    </p>

  <% end %>
</div><!--/work-box -->

app/views/blogposts/new.html.erb
<h1 class="col-md-offset-2 col-md-8 col-md-offset-2">
  New Blog Post
</h1>

<%= render 'form', blogpost: @blogpost %>

<!--<%= link_to 'Back', blogposts_path %>-->

app/views/blogposts/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1 class="col-md-offset-2 col-md-8 col-md-offset-2"><%= @blogpost.subject %></h1>

<div class="col-md-offset-2 col-md-8 col-md-offset-2 work-box">
  <h4>Posted by <%= @blogpost.author %> on <%= @blogpost.blogdate %></h4>
  <article><%= simple_format(@blogpost.blogentry) %></article>
</div><!--/work-box -->

<div class="col-md-offset-2 col-md-8 col-md-offset-2 bottom-of-page text-right">
  <% if current_user %>
    <% if @blogpost.user_id == current_user.id %>
      <%= link_to 'Edit', edit_blogpost_path(@blogpost) %>
    <% end %>
  <% end %>
</div>
<br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BomymoBlog</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-warning" role="alert"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger" role="alert"><%= alert %></p>
    <% end %>
    <nav class="navbar navbar-inverse custom-navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div><!-- end navbar-header -->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<%= blogposts_path %>">Home</a></li>
            <% if user_signed_in? %>
              <li><a href="<%= new_blogpost_path %>">New</a></li>
            <% end %>
            <li>
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
              <% else %>
                <%= link_to('Login', new_user_session_path) %>
              <% end %>
            </li>
          </ul>
        </div><!-- end nav -->
      </div><!-- end nav container -->
    </nav><!-- end navbar -->

    <%= yield %>
  
    <footer>
      <div class="footer-format">
        <p>&copy; 2017 Robert Myers-Morgan</p>
      </div>
    </footer>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>    
  </body>
</html>